FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production && npm install typescript ts-node

COPY tsconfig.json ./
COPY src ./src

CMD ["npx", "ts-node", "src/simulator/simulator.ts"]
